# Generated by Django 3.2.6 on 2021-09-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_newsprise_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPrise',
            new_name='Narh',
        ),
    ]
