# Generated by Django 3.2.6 on 2021-09-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_newsprise_narh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Narh',
        ),
    ]
