# Generated by Django 3.2.6 on 2021-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_delete_narh'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarhMaydon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=75)),
                ('narx', models.IntegerField()),
                ('tarif', models.CharField(max_length=75)),
            ],
        ),
    ]
