# Generated by Django 3.2.6 on 2021-09-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_newsprise_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsprise',
            name='title',
        ),
    ]
