version: '2'

services:
  quqondb_prod:
    container_name: quqondb_prod
    restart: always  
    image: postgres:12.2
    environment:
      POSTGRES_DB: db_quqon_prod
      POSTGRES_USER: quqonuser_prod
      POSTGRES_PASSWORD: quqonpass_prod
    networks:
      - quqon-network
    volumes:
        - quqondata:/var/lib/postgresql/quqondata/
    
  quqonweb_prod:
    container_name: quqonweb_prod
    restart: always  
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:2020
    volumes:
      - static_volume_quqon:/home/app/web/static
      - media_volume_quqon:/home/app/web/media
    networks:
      - quqon-network
    depends_on: 
      - quqondb_prod
    ports:
      - "2020:2020"
    env_file: 
      - ./.env.prod

  quqonnginx:
    container_name: quqon-nginx
    restart: always
    build: ./nginx
    volumes:
      - static_volume_quqon:/home/app/web/static
      - media_volume_quqon:/home/app/web/media
    ports:
      - "4040:4040"
    networks:
      - quqon-network
    depends_on:
      - quqonweb_prod
      
volumes:
  quqondata:
  static_volume_quqon:
  media_volume_quqon:

networks:
  quqon-network:
    driver: bridge
